title: "ECG Recognition Libraray"
date: 2022-06-20
theme: jekyll-theme-minimal
markdown: kramdown
description: > # this means to ignore newlines until "baseurl:"
  <div class='menu-group'>
    <div class='main-menu-item'><a href="/index.html">Main</a></div>
    <div class='menu-item'><a href="/proj.html">aaa</a></div>
  </div>
  <div class='menu-group'>
    <div class='main-menu-item'><a href="index.md">item1</a></div>
    <div class='menu-item'><a href="proj.md">item2</a></div>
  </div>
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
