title: "ECG Recognition Library"
date: 2022-06-20
theme: jekyll-theme-minimal
markdown: kramdown
description: > # this means to ignore newlines until "baseurl:"
  <div class='menu-group'>
    <div class='main-menu-item'><a href="/index">MAIN</a></div>
    <div class='menu-item'><a href="/proj">proj</a></div>
    <div class='menu-item'><a href="/part1/c">c</a></div>
    <div class='menu-item'><a href="/B.html">B</a></div>
  </div>
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
